openapi: 3.1.0
info:
  version: 1.0.0
  title: Toucandun strore
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of students app
tags:
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://toucan-back-end.onrender.com
paths:
  /register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
